

/* This is auto-generated code. Edit at your own peril. */
#include <stdio.h>
#include "CuTest.h"


extern void TestLog_new_is_empty(CuTest*);
extern void TestLog_append_is_not_empty(CuTest*);
extern void TestLog_get_at_idx(CuTest*);
extern void TestLog_get_at_idx_returns_null_where_out_of_bounds(CuTest*);
extern void TestLog_delete(CuTest*);
extern void TestLog_delete_onwards(CuTest*);
extern void TestLog_delete_handles_log_pop_failure(CuTest*);
extern void TestLog_delete_fails_for_idx_zero(CuTest*);
extern void TestLog_poll(CuTest*);
extern void TestLog_peektail(CuTest*);
extern void TestLog_load_from_snapshot(CuTest*);
extern void TestLog_load_from_snapshot_clears_log(CuTest*);
extern void TestLog_front_pushes_across_boundary(CuTest*);
extern void TestLog_front_and_back_pushed_across_boundary_with_enlargement_required(CuTest*);
extern void TestLog_delete_after_polling(CuTest*);
extern void TestLog_delete_after_polling_from_double_append(CuTest*);
extern void TestLog_get_from_idx_with_base_off_by_one(CuTest*);
extern void TestLog_delete_with_idx_below_base(CuTest*);
extern void TestLog_delete_with_idx_beyond_current(CuTest*);
extern void TestLog_poll_on_empty_log(CuTest*);
extern void TestLog_poll_all_entries_then_poll_empty(CuTest*);
extern void TestLog_get_at_idx_after_polling(CuTest*);
extern void TestLog_circular_buffer_wraparound(CuTest*);
extern void TestLog_count_after_mixed_poll_append(CuTest*);
extern void TestLog_new_from_base(CuTest*);
extern void TestLog_capacity_growth_multiple_reallocs(CuTest*);
extern void TestLog_peektail_on_empty_log(CuTest*);
extern void TestRaft_is_voting_by_default(CuTest*);
extern void TestRaft_node_set_nextIdx(CuTest*);
extern void TestRaft_node_get_next_idx_default_is_1(CuTest*);
extern void TestRaft_node_set_nextIdx_clamped_to_1(CuTest*);
extern void TestRaft_node_get_id(CuTest*);
extern void TestRaft_node_get_id_zero(CuTest*);
extern void TestRaft_node_udata_round_trip(CuTest*);
extern void TestRaft_node_udata_null(CuTest*);
extern void TestRaft_node_match_idx_default_is_0(CuTest*);
extern void TestRaft_node_set_match_idx(CuTest*);
extern void TestRaft_node_active_by_default(CuTest*);
extern void TestRaft_node_set_active(CuTest*);
extern void TestRaft_node_voting_committed_default_is_0(CuTest*);
extern void TestRaft_node_set_voting_committed(CuTest*);
extern void TestRaft_node_addition_committed_default_is_0(CuTest*);
extern void TestRaft_node_set_addition_committed(CuTest*);
extern void TestRaft_node_has_sufficient_logs_default_is_0(CuTest*);
extern void TestRaft_node_set_has_sufficient_logs(CuTest*);
extern void TestRaft_node_set_voting_toggle(CuTest*);
extern void TestRaft_node_vote_for_me(CuTest*);
extern void TestRaft_node_free(CuTest*);
extern void TestRaft_node_flags_independent(CuTest*);
extern void TestRaft_scenario_leader_appears(CuTest*);
extern void TestRaft_server_voted_for_records_who_we_voted_for(CuTest*);
extern void TestRaft_server_get_my_node(CuTest*);
extern void TestRaft_server_idx_starts_at_1(CuTest*);
extern void TestRaft_server_currentterm_defaults_to_0(CuTest*);
extern void TestRaft_server_set_currentterm_sets_term(CuTest*);
extern void TestRaft_server_voting_results_in_voting(CuTest*);
extern void TestRaft_server_add_node_makes_non_voting_node_voting(CuTest*);
extern void TestRaft_server_add_node_with_already_existing_id_is_not_allowed(CuTest*);
extern void TestRaft_server_add_non_voting_node_with_already_existing_id_is_not_allowed(CuTest*);
extern void TestRaft_server_add_non_voting_node_with_already_existing_voting_id_is_not_allowed(CuTest*);
extern void TestRaft_server_remove_node(CuTest*);
extern void TestRaft_election_start_increments_term(CuTest*);
extern void TestRaft_set_state(CuTest*);
extern void TestRaft_server_starts_as_follower(CuTest*);
extern void TestRaft_server_starts_with_election_timeout_of_1000ms(CuTest*);
extern void TestRaft_server_starts_with_request_timeout_of_200ms(CuTest*);
extern void TestRaft_server_entry_append_increases_logidx(CuTest*);
extern void TestRaft_server_append_entry_means_entry_gets_current_term(CuTest*);
extern void TestRaft_server_append_entry_is_retrievable(CuTest*);
extern void TestRaft_server_append_entry_user_can_set_data_buf(CuTest*);
extern void TestRaft_server_entry_is_retrieveable_using_idx(CuTest*);
extern void TestRaft_server_wont_apply_entry_if_we_dont_have_entry_to_apply(CuTest*);
extern void TestRaft_server_wont_apply_entry_if_there_isnt_a_majority(CuTest*);
extern void TestRaft_server_increment_lastApplied_when_lastApplied_lt_commitidx(CuTest*);
extern void TestRaft_user_applylog_error_propogates_to_periodic(CuTest*);
extern void TestRaft_server_apply_entry_increments_last_applied_idx(CuTest*);
extern void TestRaft_server_periodic_elapses_election_timeout(CuTest*);
extern void TestRaft_server_election_timeout_does_not_promote_us_to_leader_if_there_is_are_more_than_1_nodes(CuTest*);
extern void TestRaft_server_election_timeout_does_not_promote_us_to_leader_if_we_are_not_voting_node(CuTest*);
extern void TestRaft_server_election_timeout_does_not_start_election_if_there_are_no_voting_nodes(CuTest*);
extern void TestRaft_server_election_timeout_does_promote_us_to_leader_if_there_is_only_1_node(CuTest*);
extern void TestRaft_server_election_timeout_does_promote_us_to_leader_if_there_is_only_1_voting_node(CuTest*);
extern void TestRaft_server_recv_entry_auto_commits_if_we_are_the_only_node(CuTest*);
extern void TestRaft_server_recv_entry_fails_if_there_is_already_a_voting_change(CuTest*);
extern void TestRaft_server_cfg_sets_num_nodes(CuTest*);
extern void TestRaft_server_cant_get_node_we_dont_have(CuTest*);
extern void TestRaft_votes_are_majority_is_true(CuTest*);
extern void TestRaft_server_recv_requestvote_response_dont_increase_votes_for_me_when_not_granted(CuTest*);
extern void TestRaft_server_recv_requestvote_response_dont_increase_votes_for_me_when_term_is_not_equal(CuTest*);
extern void TestRaft_server_recv_requestvote_response_increase_votes_for_me(CuTest*);
extern void TestRaft_server_recv_requestvote_response_must_be_candidate_to_receive(CuTest*);
extern void TestRaft_server_recv_requestvote_reply_false_if_term_less_than_current_term(CuTest*);
extern void TestRaft_leader_recv_requestvote_does_not_step_down(CuTest*);
extern void TestRaft_server_recv_requestvote_reply_true_if_term_greater_than_or_equal_to_current_term(CuTest*);
extern void TestRaft_server_recv_requestvote_reset_timeout(CuTest*);
extern void TestRaft_server_recv_requestvote_candidate_step_down_if_term_is_higher_than_current_term(CuTest*);
extern void TestRaft_server_recv_requestvote_depends_on_candidate_id(CuTest*);
extern void TestRaft_server_recv_requestvote_dont_grant_vote_if_we_didnt_vote_for_this_candidate(CuTest*);
extern void TestRaft_server_recv_requestvote_ignore_if_master_is_fresh(CuTest*);
extern void TestRaft_follower_becomes_follower_is_follower(CuTest*);
extern void TestRaft_follower_becomes_follower_does_not_clear_voted_for(CuTest*);
extern void TestRaft_follower_recv_appendentries_reply_false_if_term_less_than_currentterm(CuTest*);
extern void TestRaft_follower_recv_appendentries_does_not_need_node(CuTest*);
extern void TestRaft_follower_recv_appendentries_updates_currentterm_if_term_gt_currentterm(CuTest*);
extern void TestRaft_follower_recv_appendentries_does_not_log_if_no_entries_are_specified(CuTest*);
extern void TestRaft_follower_recv_appendentries_increases_log(CuTest*);
extern void TestRaft_follower_recv_appendentries_reply_false_if_doesnt_have_log_at_prev_log_idx_which_matches_prev_log_term(CuTest*);
extern void TestRaft_follower_recv_appendentries_delete_entries_if_conflict_with_new_entries_via_prev_log_idx(CuTest*);
extern void TestRaft_follower_recv_appendentries_delete_entries_if_conflict_with_new_entries_via_prev_log_idx_at_idx_0(CuTest*);
extern void TestRaft_follower_recv_appendentries_delete_entries_if_conflict_with_new_entries_greater_than_prev_log_idx(CuTest*);
extern void TestRaft_follower_recv_appendentries_add_new_entries_not_already_in_log(CuTest*);
extern void TestRaft_follower_recv_appendentries_does_not_add_dupe_entries_already_in_log(CuTest*);
extern void TestRaft_follower_recv_appendentries_partial_failures(CuTest*);
extern void TestRaft_follower_recv_appendentries_set_commitidx_to_prevLogIdx(CuTest*);
extern void TestRaft_follower_recv_appendentries_set_commitidx_to_LeaderCommit(CuTest*);
extern void TestRaft_follower_recv_appendentries_failure_includes_current_idx(CuTest*);
extern void TestRaft_follower_becomes_candidate_when_election_timeout_occurs(CuTest*);
extern void TestRaft_follower_dont_grant_vote_if_candidate_has_a_less_complete_log(CuTest*);
extern void TestRaft_follower_recv_appendentries_heartbeat_does_not_overwrite_logs(CuTest*);
extern void TestRaft_follower_recv_appendentries_does_not_deleted_commited_entries(CuTest*);
extern void TestRaft_candidate_becomes_candidate_is_candidate(CuTest*);
extern void TestRaft_follower_becoming_candidate_increments_current_term(CuTest*);
extern void TestRaft_follower_becoming_candidate_votes_for_self(CuTest*);
extern void TestRaft_follower_becoming_candidate_resets_election_timeout(CuTest*);
extern void TestRaft_follower_recv_appendentries_resets_election_timeout(CuTest*);
extern void TestRaft_follower_becoming_candidate_requests_votes_from_other_servers(CuTest*);
extern void TestRaft_candidate_election_timeout_and_no_leader_results_in_new_election(CuTest*);
extern void TestRaft_candidate_receives_majority_of_votes_becomes_leader(CuTest*);
extern void TestRaft_candidate_will_not_respond_to_voterequest_if_it_has_already_voted(CuTest*);
extern void TestRaft_candidate_requestvote_includes_logidx(CuTest*);
extern void TestRaft_candidate_recv_requestvote_response_becomes_follower_if_current_term_is_less_than_term(CuTest*);
extern void TestRaft_candidate_recv_appendentries_frm_leader_results_in_follower(CuTest*);
extern void TestRaft_candidate_recv_appendentries_from_same_term_results_in_step_down(CuTest*);
extern void TestRaft_leader_becomes_leader_is_leader(CuTest*);
extern void TestRaft_leader_becomes_leader_does_not_clear_voted_for(CuTest*);
extern void TestRaft_leader_when_becomes_leader_all_nodes_have_nextidx_equal_to_lastlog_idx_plus_1(CuTest*);
extern void TestRaft_leader_when_it_becomes_a_leader_sends_empty_appendentries(CuTest*);
extern void TestRaft_leader_responds_to_entry_msg_when_entry_is_committed(CuTest*);
extern void TestRaft_non_leader_recv_entry_msg_fails(CuTest*);
extern void TestRaft_leader_sends_appendentries_with_NextIdx_when_PrevIdx_gt_NextIdx(CuTest*);
extern void TestRaft_leader_sends_appendentries_with_leader_commit(CuTest*);
extern void TestRaft_leader_sends_appendentries_with_prevLogIdx(CuTest*);
extern void TestRaft_leader_sends_appendentries_when_node_has_next_idx_of_0(CuTest*);
extern void TestRaft_leader_retries_appendentries_with_decremented_NextIdx_log_inconsistency(CuTest*);
extern void TestRaft_leader_append_entry_to_log_increases_idxno(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_increase_commit_idx_when_majority_have_entry_and_atleast_one_newer_entry(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_set_has_sufficient_logs_for_node(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_increase_commit_idx_using_voting_nodes_majority(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_duplicate_does_not_decrement_match_idx(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_do_not_increase_commit_idx_because_of_old_terms_with_majority(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_jumps_to_lower_next_idx(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_decrements_to_lower_next_idx(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_retry_only_if_leader(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_without_node_fails(CuTest*);
extern void TestRaft_leader_recv_entry_resets_election_timeout(CuTest*);
extern void TestRaft_leader_recv_entry_is_committed_returns_0_if_not_committed(CuTest*);
extern void TestRaft_leader_recv_entry_is_committed_returns_neg_1_if_invalidated(CuTest*);
extern void TestRaft_leader_recv_entry_fails_if_prevlogidx_less_than_commit(CuTest*);
extern void TestRaft_leader_recv_entry_does_not_send_new_appendentries_to_slow_nodes(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_failure_does_not_set_node_nextid_to_0(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_increment_idx_of_node(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_drop_message_if_term_is_old(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_steps_down_if_term_is_newer(CuTest*);
extern void TestRaft_leader_recv_appendentries_steps_down_if_newer(CuTest*);
extern void TestRaft_leader_recv_appendentries_steps_down_if_newer_term(CuTest*);
extern void TestRaft_leader_sends_empty_appendentries_every_request_timeout(CuTest*);
extern void TestRaft_leader_recv_requestvote_responds_without_granting(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_set_has_sufficient_logs_after_voting_committed(CuTest*);
extern void TestRaft_server_get_current_leader_defaults_to_neg1(CuTest*);
extern void TestRaft_server_get_current_leader_node_defaults_to_null(CuTest*);
extern void TestRaft_server_get_current_leader_node_returns_leader(CuTest*);
extern void TestRaft_server_get_last_applied_entry_defaults_to_null(CuTest*);
extern void TestRaft_server_get_last_applied_entry_returns_correct_entry(CuTest*);
extern void TestRaft_server_get_last_log_term_defaults_to_0(CuTest*);
extern void TestRaft_server_get_last_log_term_returns_term_of_last_entry(CuTest*);
extern void TestRaft_server_get_num_voting_nodes_with_mix(CuTest*);
extern void TestRaft_server_get_udata_returns_user_data(CuTest*);
extern void TestRaft_server_get_udata_defaults_to_null(CuTest*);
extern void TestRaft_server_get_snapshot_last_idx_defaults_to_0(CuTest*);
extern void TestRaft_server_get_snapshot_last_term_defaults_to_0(CuTest*);
extern void TestRaft_server_get_first_entry_idx_defaults_to_1(CuTest*);
extern void TestRaft_server_get_state_returns_correct_states(CuTest*);
extern void TestRaft_server_get_nodeid_defaults_to_neg1(CuTest*);
extern void TestRaft_server_get_nodeid_returns_self_id(CuTest*);
extern void TestRaft_server_get_my_node_defaults_to_null(CuTest*);
extern void TestRaft_server_is_apply_allowed_defaults_to_1(CuTest*);
extern void TestRaft_server_is_apply_allowed_returns_0_during_snapshot(CuTest*);
extern void TestRaft_server_is_apply_allowed_returns_1_during_nonblocking_snapshot(CuTest*);
extern void TestRaft_server_persist_term_fail_propagates_from_set_current_term(CuTest*);
extern void TestRaft_server_persist_vote_fail_propagates_from_vote_for_nodeid(CuTest*);
extern void TestRaft_server_log_offer_fail_propagates_from_append_entry(CuTest*);
extern void TestRaft_server_log_offer_shutdown_propagates_from_append_entry(CuTest*);
extern void TestRaft_server_send_appendentries_fail_propagates_from_send_all(CuTest*);
extern void TestRaft_server_applylog_shutdown_propagates_from_periodic(CuTest*);
extern void TestRaft_server_log_poll_fail_propagates_from_poll_entry(CuTest*);
extern void TestRaft_server_log_pop_fail_propagates_from_delete_entry(CuTest*);
extern void TestRaft_server_persist_term_fail_in_recv_requestvote(CuTest*);
extern void TestRaft_server_persist_vote_fail_in_recv_requestvote(CuTest*);
extern void TestRaft_follower_dont_grant_vote_if_candidate_log_is_shorter_same_term(CuTest*);
extern void TestRaft_follower_dont_grant_vote_if_candidate_last_log_term_is_lower(CuTest*);
extern void TestRaft_follower_grant_vote_when_log_is_empty(CuTest*);
extern void TestRaft_follower_grant_vote_uses_snapshot_term_when_entry_is_null(CuTest*);
extern void TestRaft_election_timeout_with_zero_elapsed_does_not_trigger(CuTest*);
extern void TestRaft_candidate_recv_requestvote_from_other_candidate_same_term(CuTest*);
extern void TestRaft_candidate_duplicate_vote_response_does_not_double_count(CuTest*);
extern void TestRaft_candidate_nvotes_for_me_includes_self_vote(CuTest*);
extern void TestRaft_follower_rejects_vote_if_already_voted_for_another(CuTest*);
extern void TestRaft_non_voting_node_does_not_grant_vote(CuTest*);
extern void TestRaft_follower_recv_appendentries_first_entry_prev_log_idx_0(CuTest*);
extern void TestRaft_follower_recv_appendentries_delete_entries_if_term_is_different(CuTest*);
extern void TestRaft_follower_recv_appendentries_partial_overlap_some_match_some_new(CuTest*);
extern void TestRaft_follower_recv_appendentries_leader_commit_capped_to_current_idx(CuTest*);
extern void TestRaft_follower_recv_appendentries_commit_idx_not_decreased(CuTest*);
extern void TestRaft_follower_recv_appendentries_heartbeat_updates_commit_idx(CuTest*);
extern void TestRaft_follower_recv_appendentries_prev_log_idx_in_compacted_region(CuTest*);
extern void TestRaft_follower_recv_appendentries_snapshot_prev_log_term_mismatch(CuTest*);
extern void TestRaft_leader_recv_appendentries_response_with_current_idx_0(CuTest*);
extern void TestRaft_leader_begin_snapshot_fails_if_no_logs_to_compact(CuTest*);
extern void TestRaft_leader_will_not_apply_entry_if_snapshot_is_in_progress(CuTest*);
extern void TestRaft_leader_snapshot_end_fails_if_snapshot_not_in_progress(CuTest*);
extern void TestRaft_leader_snapshot_begin_fails_if_less_than_2_logs_to_compact(CuTest*);
extern void TestRaft_leader_snapshot_end_succeeds_if_log_compacted(CuTest*);
extern void TestRaft_leader_snapshot_end_succeeds_if_log_compacted2(CuTest*);
extern void TestRaft_joinee_needs_to_get_snapshot(CuTest*);
extern void TestRaft_follower_load_from_snapshot(CuTest*);
extern void TestRaft_follower_load_from_snapshot_fails_if_term_is_0(CuTest*);
extern void TestRaft_follower_load_from_snapshot_fails_if_already_loaded(CuTest*);
extern void TestRaft_follower_load_from_snapshot_does_not_break_cluster_safety(CuTest*);
extern void TestRaft_follower_load_from_snapshot_fails_if_log_is_newer(CuTest*);
extern void TestRaft_leader_sends_appendentries_when_node_next_index_was_compacted(CuTest*);
extern void TestRaft_recv_entry_fails_if_snapshot_in_progress(CuTest*);
extern void TestRaft_recv_entry_succeeds_if_snapshot_nonblocking_apply_is_set(CuTest*);
extern void TestRaft_follower_recv_appendentries_is_successful_when_previous_log_idx_equals_snapshot_last_idx(CuTest*);
extern void TestRaft_leader_sends_appendentries_with_correct_prev_log_idx_when_snapshotted(CuTest*);
extern void TestRaft_cancel_snapshot_restores_state(CuTest*);
extern void TestRaft_leader_sends_snapshot_if_log_was_compacted(CuTest*);


int RunAllTests(void)
{
    CuString *output = CuStringNew();
    CuSuite* suite = CuSuiteNew();


    SUITE_ADD_TEST(suite, TestLog_new_is_empty);
    SUITE_ADD_TEST(suite, TestLog_append_is_not_empty);
    SUITE_ADD_TEST(suite, TestLog_get_at_idx);
    SUITE_ADD_TEST(suite, TestLog_get_at_idx_returns_null_where_out_of_bounds);
    SUITE_ADD_TEST(suite, TestLog_delete);
    SUITE_ADD_TEST(suite, TestLog_delete_onwards);
    SUITE_ADD_TEST(suite, TestLog_delete_handles_log_pop_failure);
    SUITE_ADD_TEST(suite, TestLog_delete_fails_for_idx_zero);
    SUITE_ADD_TEST(suite, TestLog_poll);
    SUITE_ADD_TEST(suite, TestLog_peektail);
    SUITE_ADD_TEST(suite, TestLog_load_from_snapshot);
    SUITE_ADD_TEST(suite, TestLog_load_from_snapshot_clears_log);
    SUITE_ADD_TEST(suite, TestLog_front_pushes_across_boundary);
    SUITE_ADD_TEST(suite, TestLog_front_and_back_pushed_across_boundary_with_enlargement_required);
    SUITE_ADD_TEST(suite, TestLog_delete_after_polling);
    SUITE_ADD_TEST(suite, TestLog_delete_after_polling_from_double_append);
    SUITE_ADD_TEST(suite, TestLog_get_from_idx_with_base_off_by_one);
    SUITE_ADD_TEST(suite, TestLog_delete_with_idx_below_base);
    SUITE_ADD_TEST(suite, TestLog_delete_with_idx_beyond_current);
    SUITE_ADD_TEST(suite, TestLog_poll_on_empty_log);
    SUITE_ADD_TEST(suite, TestLog_poll_all_entries_then_poll_empty);
    SUITE_ADD_TEST(suite, TestLog_get_at_idx_after_polling);
    SUITE_ADD_TEST(suite, TestLog_circular_buffer_wraparound);
    SUITE_ADD_TEST(suite, TestLog_count_after_mixed_poll_append);
    SUITE_ADD_TEST(suite, TestLog_new_from_base);
    SUITE_ADD_TEST(suite, TestLog_capacity_growth_multiple_reallocs);
    SUITE_ADD_TEST(suite, TestLog_peektail_on_empty_log);
    SUITE_ADD_TEST(suite, TestRaft_is_voting_by_default);
    SUITE_ADD_TEST(suite, TestRaft_node_set_nextIdx);
    SUITE_ADD_TEST(suite, TestRaft_node_get_next_idx_default_is_1);
    SUITE_ADD_TEST(suite, TestRaft_node_set_nextIdx_clamped_to_1);
    SUITE_ADD_TEST(suite, TestRaft_node_get_id);
    SUITE_ADD_TEST(suite, TestRaft_node_get_id_zero);
    SUITE_ADD_TEST(suite, TestRaft_node_udata_round_trip);
    SUITE_ADD_TEST(suite, TestRaft_node_udata_null);
    SUITE_ADD_TEST(suite, TestRaft_node_match_idx_default_is_0);
    SUITE_ADD_TEST(suite, TestRaft_node_set_match_idx);
    SUITE_ADD_TEST(suite, TestRaft_node_active_by_default);
    SUITE_ADD_TEST(suite, TestRaft_node_set_active);
    SUITE_ADD_TEST(suite, TestRaft_node_voting_committed_default_is_0);
    SUITE_ADD_TEST(suite, TestRaft_node_set_voting_committed);
    SUITE_ADD_TEST(suite, TestRaft_node_addition_committed_default_is_0);
    SUITE_ADD_TEST(suite, TestRaft_node_set_addition_committed);
    SUITE_ADD_TEST(suite, TestRaft_node_has_sufficient_logs_default_is_0);
    SUITE_ADD_TEST(suite, TestRaft_node_set_has_sufficient_logs);
    SUITE_ADD_TEST(suite, TestRaft_node_set_voting_toggle);
    SUITE_ADD_TEST(suite, TestRaft_node_vote_for_me);
    SUITE_ADD_TEST(suite, TestRaft_node_free);
    SUITE_ADD_TEST(suite, TestRaft_node_flags_independent);
    SUITE_ADD_TEST(suite, TestRaft_scenario_leader_appears);
    SUITE_ADD_TEST(suite, TestRaft_server_voted_for_records_who_we_voted_for);
    SUITE_ADD_TEST(suite, TestRaft_server_get_my_node);
    SUITE_ADD_TEST(suite, TestRaft_server_idx_starts_at_1);
    SUITE_ADD_TEST(suite, TestRaft_server_currentterm_defaults_to_0);
    SUITE_ADD_TEST(suite, TestRaft_server_set_currentterm_sets_term);
    SUITE_ADD_TEST(suite, TestRaft_server_voting_results_in_voting);
    SUITE_ADD_TEST(suite, TestRaft_server_add_node_makes_non_voting_node_voting);
    SUITE_ADD_TEST(suite, TestRaft_server_add_node_with_already_existing_id_is_not_allowed);
    SUITE_ADD_TEST(suite, TestRaft_server_add_non_voting_node_with_already_existing_id_is_not_allowed);
    SUITE_ADD_TEST(suite, TestRaft_server_add_non_voting_node_with_already_existing_voting_id_is_not_allowed);
    SUITE_ADD_TEST(suite, TestRaft_server_remove_node);
    SUITE_ADD_TEST(suite, TestRaft_election_start_increments_term);
    SUITE_ADD_TEST(suite, TestRaft_set_state);
    SUITE_ADD_TEST(suite, TestRaft_server_starts_as_follower);
    SUITE_ADD_TEST(suite, TestRaft_server_starts_with_election_timeout_of_1000ms);
    SUITE_ADD_TEST(suite, TestRaft_server_starts_with_request_timeout_of_200ms);
    SUITE_ADD_TEST(suite, TestRaft_server_entry_append_increases_logidx);
    SUITE_ADD_TEST(suite, TestRaft_server_append_entry_means_entry_gets_current_term);
    SUITE_ADD_TEST(suite, TestRaft_server_append_entry_is_retrievable);
    SUITE_ADD_TEST(suite, TestRaft_server_append_entry_user_can_set_data_buf);
    SUITE_ADD_TEST(suite, TestRaft_server_entry_is_retrieveable_using_idx);
    SUITE_ADD_TEST(suite, TestRaft_server_wont_apply_entry_if_we_dont_have_entry_to_apply);
    SUITE_ADD_TEST(suite, TestRaft_server_wont_apply_entry_if_there_isnt_a_majority);
    SUITE_ADD_TEST(suite, TestRaft_server_increment_lastApplied_when_lastApplied_lt_commitidx);
    SUITE_ADD_TEST(suite, TestRaft_user_applylog_error_propogates_to_periodic);
    SUITE_ADD_TEST(suite, TestRaft_server_apply_entry_increments_last_applied_idx);
    SUITE_ADD_TEST(suite, TestRaft_server_periodic_elapses_election_timeout);
    SUITE_ADD_TEST(suite, TestRaft_server_election_timeout_does_not_promote_us_to_leader_if_there_is_are_more_than_1_nodes);
    SUITE_ADD_TEST(suite, TestRaft_server_election_timeout_does_not_promote_us_to_leader_if_we_are_not_voting_node);
    SUITE_ADD_TEST(suite, TestRaft_server_election_timeout_does_not_start_election_if_there_are_no_voting_nodes);
    SUITE_ADD_TEST(suite, TestRaft_server_election_timeout_does_promote_us_to_leader_if_there_is_only_1_node);
    SUITE_ADD_TEST(suite, TestRaft_server_election_timeout_does_promote_us_to_leader_if_there_is_only_1_voting_node);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_entry_auto_commits_if_we_are_the_only_node);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_entry_fails_if_there_is_already_a_voting_change);
    SUITE_ADD_TEST(suite, TestRaft_server_cfg_sets_num_nodes);
    SUITE_ADD_TEST(suite, TestRaft_server_cant_get_node_we_dont_have);
    SUITE_ADD_TEST(suite, TestRaft_votes_are_majority_is_true);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_response_dont_increase_votes_for_me_when_not_granted);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_response_dont_increase_votes_for_me_when_term_is_not_equal);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_response_increase_votes_for_me);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_response_must_be_candidate_to_receive);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_reply_false_if_term_less_than_current_term);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_requestvote_does_not_step_down);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_reply_true_if_term_greater_than_or_equal_to_current_term);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_reset_timeout);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_candidate_step_down_if_term_is_higher_than_current_term);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_depends_on_candidate_id);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_dont_grant_vote_if_we_didnt_vote_for_this_candidate);
    SUITE_ADD_TEST(suite, TestRaft_server_recv_requestvote_ignore_if_master_is_fresh);
    SUITE_ADD_TEST(suite, TestRaft_follower_becomes_follower_is_follower);
    SUITE_ADD_TEST(suite, TestRaft_follower_becomes_follower_does_not_clear_voted_for);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_reply_false_if_term_less_than_currentterm);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_does_not_need_node);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_updates_currentterm_if_term_gt_currentterm);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_does_not_log_if_no_entries_are_specified);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_increases_log);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_reply_false_if_doesnt_have_log_at_prev_log_idx_which_matches_prev_log_term);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_delete_entries_if_conflict_with_new_entries_via_prev_log_idx);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_delete_entries_if_conflict_with_new_entries_via_prev_log_idx_at_idx_0);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_delete_entries_if_conflict_with_new_entries_greater_than_prev_log_idx);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_add_new_entries_not_already_in_log);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_does_not_add_dupe_entries_already_in_log);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_partial_failures);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_set_commitidx_to_prevLogIdx);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_set_commitidx_to_LeaderCommit);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_failure_includes_current_idx);
    SUITE_ADD_TEST(suite, TestRaft_follower_becomes_candidate_when_election_timeout_occurs);
    SUITE_ADD_TEST(suite, TestRaft_follower_dont_grant_vote_if_candidate_has_a_less_complete_log);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_heartbeat_does_not_overwrite_logs);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_does_not_deleted_commited_entries);
    SUITE_ADD_TEST(suite, TestRaft_candidate_becomes_candidate_is_candidate);
    SUITE_ADD_TEST(suite, TestRaft_follower_becoming_candidate_increments_current_term);
    SUITE_ADD_TEST(suite, TestRaft_follower_becoming_candidate_votes_for_self);
    SUITE_ADD_TEST(suite, TestRaft_follower_becoming_candidate_resets_election_timeout);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_resets_election_timeout);
    SUITE_ADD_TEST(suite, TestRaft_follower_becoming_candidate_requests_votes_from_other_servers);
    SUITE_ADD_TEST(suite, TestRaft_candidate_election_timeout_and_no_leader_results_in_new_election);
    SUITE_ADD_TEST(suite, TestRaft_candidate_receives_majority_of_votes_becomes_leader);
    SUITE_ADD_TEST(suite, TestRaft_candidate_will_not_respond_to_voterequest_if_it_has_already_voted);
    SUITE_ADD_TEST(suite, TestRaft_candidate_requestvote_includes_logidx);
    SUITE_ADD_TEST(suite, TestRaft_candidate_recv_requestvote_response_becomes_follower_if_current_term_is_less_than_term);
    SUITE_ADD_TEST(suite, TestRaft_candidate_recv_appendentries_frm_leader_results_in_follower);
    SUITE_ADD_TEST(suite, TestRaft_candidate_recv_appendentries_from_same_term_results_in_step_down);
    SUITE_ADD_TEST(suite, TestRaft_leader_becomes_leader_is_leader);
    SUITE_ADD_TEST(suite, TestRaft_leader_becomes_leader_does_not_clear_voted_for);
    SUITE_ADD_TEST(suite, TestRaft_leader_when_becomes_leader_all_nodes_have_nextidx_equal_to_lastlog_idx_plus_1);
    SUITE_ADD_TEST(suite, TestRaft_leader_when_it_becomes_a_leader_sends_empty_appendentries);
    SUITE_ADD_TEST(suite, TestRaft_leader_responds_to_entry_msg_when_entry_is_committed);
    SUITE_ADD_TEST(suite, TestRaft_non_leader_recv_entry_msg_fails);
    SUITE_ADD_TEST(suite, TestRaft_leader_sends_appendentries_with_NextIdx_when_PrevIdx_gt_NextIdx);
    SUITE_ADD_TEST(suite, TestRaft_leader_sends_appendentries_with_leader_commit);
    SUITE_ADD_TEST(suite, TestRaft_leader_sends_appendentries_with_prevLogIdx);
    SUITE_ADD_TEST(suite, TestRaft_leader_sends_appendentries_when_node_has_next_idx_of_0);
    SUITE_ADD_TEST(suite, TestRaft_leader_retries_appendentries_with_decremented_NextIdx_log_inconsistency);
    SUITE_ADD_TEST(suite, TestRaft_leader_append_entry_to_log_increases_idxno);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_increase_commit_idx_when_majority_have_entry_and_atleast_one_newer_entry);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_set_has_sufficient_logs_for_node);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_increase_commit_idx_using_voting_nodes_majority);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_duplicate_does_not_decrement_match_idx);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_do_not_increase_commit_idx_because_of_old_terms_with_majority);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_jumps_to_lower_next_idx);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_decrements_to_lower_next_idx);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_retry_only_if_leader);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_without_node_fails);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_entry_resets_election_timeout);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_entry_is_committed_returns_0_if_not_committed);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_entry_is_committed_returns_neg_1_if_invalidated);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_entry_fails_if_prevlogidx_less_than_commit);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_entry_does_not_send_new_appendentries_to_slow_nodes);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_failure_does_not_set_node_nextid_to_0);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_increment_idx_of_node);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_drop_message_if_term_is_old);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_steps_down_if_term_is_newer);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_steps_down_if_newer);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_steps_down_if_newer_term);
    SUITE_ADD_TEST(suite, TestRaft_leader_sends_empty_appendentries_every_request_timeout);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_requestvote_responds_without_granting);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_set_has_sufficient_logs_after_voting_committed);
    SUITE_ADD_TEST(suite, TestRaft_server_get_current_leader_defaults_to_neg1);
    SUITE_ADD_TEST(suite, TestRaft_server_get_current_leader_node_defaults_to_null);
    SUITE_ADD_TEST(suite, TestRaft_server_get_current_leader_node_returns_leader);
    SUITE_ADD_TEST(suite, TestRaft_server_get_last_applied_entry_defaults_to_null);
    SUITE_ADD_TEST(suite, TestRaft_server_get_last_applied_entry_returns_correct_entry);
    SUITE_ADD_TEST(suite, TestRaft_server_get_last_log_term_defaults_to_0);
    SUITE_ADD_TEST(suite, TestRaft_server_get_last_log_term_returns_term_of_last_entry);
    SUITE_ADD_TEST(suite, TestRaft_server_get_num_voting_nodes_with_mix);
    SUITE_ADD_TEST(suite, TestRaft_server_get_udata_returns_user_data);
    SUITE_ADD_TEST(suite, TestRaft_server_get_udata_defaults_to_null);
    SUITE_ADD_TEST(suite, TestRaft_server_get_snapshot_last_idx_defaults_to_0);
    SUITE_ADD_TEST(suite, TestRaft_server_get_snapshot_last_term_defaults_to_0);
    SUITE_ADD_TEST(suite, TestRaft_server_get_first_entry_idx_defaults_to_1);
    SUITE_ADD_TEST(suite, TestRaft_server_get_state_returns_correct_states);
    SUITE_ADD_TEST(suite, TestRaft_server_get_nodeid_defaults_to_neg1);
    SUITE_ADD_TEST(suite, TestRaft_server_get_nodeid_returns_self_id);
    SUITE_ADD_TEST(suite, TestRaft_server_get_my_node_defaults_to_null);
    SUITE_ADD_TEST(suite, TestRaft_server_is_apply_allowed_defaults_to_1);
    SUITE_ADD_TEST(suite, TestRaft_server_is_apply_allowed_returns_0_during_snapshot);
    SUITE_ADD_TEST(suite, TestRaft_server_is_apply_allowed_returns_1_during_nonblocking_snapshot);
    SUITE_ADD_TEST(suite, TestRaft_server_persist_term_fail_propagates_from_set_current_term);
    SUITE_ADD_TEST(suite, TestRaft_server_persist_vote_fail_propagates_from_vote_for_nodeid);
    SUITE_ADD_TEST(suite, TestRaft_server_log_offer_fail_propagates_from_append_entry);
    SUITE_ADD_TEST(suite, TestRaft_server_log_offer_shutdown_propagates_from_append_entry);
    SUITE_ADD_TEST(suite, TestRaft_server_send_appendentries_fail_propagates_from_send_all);
    SUITE_ADD_TEST(suite, TestRaft_server_applylog_shutdown_propagates_from_periodic);
    SUITE_ADD_TEST(suite, TestRaft_server_log_poll_fail_propagates_from_poll_entry);
    SUITE_ADD_TEST(suite, TestRaft_server_log_pop_fail_propagates_from_delete_entry);
    SUITE_ADD_TEST(suite, TestRaft_server_persist_term_fail_in_recv_requestvote);
    SUITE_ADD_TEST(suite, TestRaft_server_persist_vote_fail_in_recv_requestvote);
    SUITE_ADD_TEST(suite, TestRaft_follower_dont_grant_vote_if_candidate_log_is_shorter_same_term);
    SUITE_ADD_TEST(suite, TestRaft_follower_dont_grant_vote_if_candidate_last_log_term_is_lower);
    SUITE_ADD_TEST(suite, TestRaft_follower_grant_vote_when_log_is_empty);
    SUITE_ADD_TEST(suite, TestRaft_follower_grant_vote_uses_snapshot_term_when_entry_is_null);
    SUITE_ADD_TEST(suite, TestRaft_election_timeout_with_zero_elapsed_does_not_trigger);
    SUITE_ADD_TEST(suite, TestRaft_candidate_recv_requestvote_from_other_candidate_same_term);
    SUITE_ADD_TEST(suite, TestRaft_candidate_duplicate_vote_response_does_not_double_count);
    SUITE_ADD_TEST(suite, TestRaft_candidate_nvotes_for_me_includes_self_vote);
    SUITE_ADD_TEST(suite, TestRaft_follower_rejects_vote_if_already_voted_for_another);
    SUITE_ADD_TEST(suite, TestRaft_non_voting_node_does_not_grant_vote);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_first_entry_prev_log_idx_0);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_delete_entries_if_term_is_different);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_partial_overlap_some_match_some_new);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_leader_commit_capped_to_current_idx);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_commit_idx_not_decreased);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_heartbeat_updates_commit_idx);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_prev_log_idx_in_compacted_region);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_snapshot_prev_log_term_mismatch);
    SUITE_ADD_TEST(suite, TestRaft_leader_recv_appendentries_response_with_current_idx_0);
    SUITE_ADD_TEST(suite, TestRaft_leader_begin_snapshot_fails_if_no_logs_to_compact);
    SUITE_ADD_TEST(suite, TestRaft_leader_will_not_apply_entry_if_snapshot_is_in_progress);
    SUITE_ADD_TEST(suite, TestRaft_leader_snapshot_end_fails_if_snapshot_not_in_progress);
    SUITE_ADD_TEST(suite, TestRaft_leader_snapshot_begin_fails_if_less_than_2_logs_to_compact);
    SUITE_ADD_TEST(suite, TestRaft_leader_snapshot_end_succeeds_if_log_compacted);
    SUITE_ADD_TEST(suite, TestRaft_leader_snapshot_end_succeeds_if_log_compacted2);
    SUITE_ADD_TEST(suite, TestRaft_joinee_needs_to_get_snapshot);
    SUITE_ADD_TEST(suite, TestRaft_follower_load_from_snapshot);
    SUITE_ADD_TEST(suite, TestRaft_follower_load_from_snapshot_fails_if_term_is_0);
    SUITE_ADD_TEST(suite, TestRaft_follower_load_from_snapshot_fails_if_already_loaded);
    SUITE_ADD_TEST(suite, TestRaft_follower_load_from_snapshot_does_not_break_cluster_safety);
    SUITE_ADD_TEST(suite, TestRaft_follower_load_from_snapshot_fails_if_log_is_newer);
    SUITE_ADD_TEST(suite, TestRaft_leader_sends_appendentries_when_node_next_index_was_compacted);
    SUITE_ADD_TEST(suite, TestRaft_recv_entry_fails_if_snapshot_in_progress);
    SUITE_ADD_TEST(suite, TestRaft_recv_entry_succeeds_if_snapshot_nonblocking_apply_is_set);
    SUITE_ADD_TEST(suite, TestRaft_follower_recv_appendentries_is_successful_when_previous_log_idx_equals_snapshot_last_idx);
    SUITE_ADD_TEST(suite, TestRaft_leader_sends_appendentries_with_correct_prev_log_idx_when_snapshotted);
    SUITE_ADD_TEST(suite, TestRaft_cancel_snapshot_restores_state);
    SUITE_ADD_TEST(suite, TestRaft_leader_sends_snapshot_if_log_was_compacted);

    CuSuiteRun(suite);
    CuSuiteDetails(suite, output);
    printf("%s\\n", output->buffer);
    return suite->failCount == 0 ? 0 : 1;
}

int main()
{
    return RunAllTests();
}

